[package]
edition = "2018"
name = "bonaventure"
version = "0.1.0"
authors = ["Will Duquette <will@wjduquette.com>"]

[dependencies]
textwrap = { version = "0.11", features = ["term_size"] }
rustyline = "3.0.0"
